export const actionTypes = {
    SIGNUP: 'SIGNUP',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    SIGNIN: 'SIGNIN',
    SIGNIN_START: 'SIGNIN_START',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS'
};
