export const actionTypes = {
    SIGNUP: 'SIGNUP',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    SIGNIN: 'SIGNIN',
    SIGNIN_START: 'SIGNIN_START',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',

    SIGNOUT: 'SIGNOUT',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_ERROR: 'SIGNOUT_ERROR',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    
    REQ_LOGGED_USER: 'REQ_LOGGED_USER',
    REQ_LOGGED_USER_START: 'REQ_LOGGED_USER_START',
    REQ_LOGGED_USER_ERROR: 'REQ_LOGGED_USER_ERROR',
    REQ_LOGGED_USER_SUCCESS: 'REQ_LOGGED_USER_SUCCESS',

    REQUEST_ERROR: 'REQUEST_ERROR'
};
