export const actionTypes = {
    BUSCA_DOCUMENTOS: 'BUSCA_DOCUMENTOS',
    BUSCA_DOCUMENTOS_START: 'BUSCA_DOCUMENTOS_START',
    BUSCA_DOCUMENTOS_ERROR: 'BUSCA_DOCUMENTOS_ERROR',
    BUSCA_DOCUMENTOS_SUCCESS: 'BUSCA_DOCUMENTOS_SUCCESS'
};
